### ISSUE TITLE
real launch lcm_server error

### ISSUE THREAD

**Issue by sasilva1998** [unitreerobotics/unitree_ros_to_real#20]
Hi, so I have been able to compile the workspace successfully and connected through wifi to the A1 robot I have, I can ping the IP address from the robot. Now I am running the following command:

````
roslaunch unitree_legged_real real.launch ctrl_level:=highlevel
````

However I am getting the following error:

````
/home/sasm/catkin_ws/devel/lib/unitree_legged_real/lcm_server: symbol lookup error: /home/sasm/catkin_ws/devel/lib/unitree_legged_real/lcm_server: undefined symbol: _ZN18UNITREE_LEGGED_SDK3UDPC1EtPKctiii
[node_lcm_server-2] process has died [pid 9102, exit code 127, cmd /home/sasm/catkin_ws/devel/lib/unitree_legged_real/lcm_server highlevel __name:=node_lcm_server __log:=/home/sasm/.ros/log/0d0ad60c-9c8f-11ec-bd2d-2c6dc1124c6f/node_lcm_server-2.log].
log file: /home/sasm/.ros/log/0d0ad60c-9c8f-11ec-bd2d-2c6dc1124c6f/node_lcm_server-2*.log
````

I suppose it is something that has to be with the UDP configuration. I would like to know what is wrong. Can somebody guide me? Thanks

**Comment by GradiusTwinbee** [comment]
We are confronting the same problem...

**Comment by GradiusTwinbee** [comment]
sorry, not yet.....

**Comment by GradiusTwinbee** [comment]
Hey，the staff from Unitree told me that the package "unitree_ros_to_real" doesn't support new versions of moving procedures anymore. The only thing you can do is to use the package "unitree_legged_sdk". In this package, you may find some demos and their source codes, from which you can learn how to control the dog by coding. You can also introduce ros into these codes.

**Comment by ROSNovice** [comment]
> Hi, so I have been able to compile the workspace successfully and connected through wifi to the A1 robot I have, I can ping the IP address from the robot. Now I am running the following command:
> 
> ```
> roslaunch unitree_legged_real real.launch ctrl_level:=highlevel
> ```
> 
> However I am getting the following error:
> 
> ```
> /home/sasm/catkin_ws/devel/lib/unitree_legged_real/lcm_server: symbol lookup error: /home/sasm/catkin_ws/devel/lib/unitree_legged_real/lcm_server: undefined symbol: _ZN18UNITREE_LEGGED_SDK3UDPC1EtPKctiii
> [node_lcm_server-2] process has died [pid 9102, exit code 127, cmd /home/sasm/catkin_ws/devel/lib/unitree_legged_real/lcm_server highlevel __name:=node_lcm_server __log:=/home/sasm/.ros/log/0d0ad60c-9c8f-11ec-bd2d-2c6dc1124c6f/node_lcm_server-2.log].
> log file: /home/sasm/.ros/log/0d0ad60c-9c8f-11ec-bd2d-2c6dc1124c6f/node_lcm_server-2*.log
> ```
> 
> I suppose it is something that has to be with the UDP configuration. I would like to know what is wrong. Can somebody guide me? Thanks

hi may i know the detail which tutorial about connection between unitree and remote pc
?

**Comment by sasilva1998** [comment]
> Hey，the staff from Unitree told me that the package "unitree_ros_to_real" doesn't support new versions of moving procedures anymore. The only thing you can do is to use the package "unitree_legged_sdk". In this package, you may find some demos and their source codes, from which you can learn how to control the dog by coding. You can also introduce ros into these codes.

@GradiusTwinbee in the end I could make it work last week finally, I could move the robot via wifi from an external PC. Could you?

@ROSNovice there are some tutorials to do that [http://wiki.ros.org/ROS/Tutorials/MultipleMachines](http://wiki.ros.org/ROS/Tutorials/MultipleMachines)
