### ISSUE TITLE
problem with unitree_ros_real, GO1 robot

### ISSUE THREAD

**Issue by gerardoportilla** [unitreerobotics/unitree_ros_to_real#30]
Hello!!
robot:GO1.
I have a problem when using unitree _ros_real, at high level, I manage to connect the LCM, as well as when executing the walk_lcm node, and I can get the data from the sensors, but the commands to walk are not sent.

I had the same problem with the SDK, so I fixed it by adding the levelFlag=0 command; Now the SDK works perfectly.

however in ros I have added this code SendHighROS.levelFlag =0; but it doesn't work, I'm still only getting the data from the robot's sensors, but the commands are not sent.

I would be grateful if you could help me solve this problem.

**Comment by gerardoportilla** [comment]
Hello Antoni
the levelFLag =0, is put before the cmd.mode = 0; inside the Custom::RobotControl() void.  in the example_walk.cpp file

For this reason I tried the same in ros, with SendHighROS.levelFlag =0 or SendHighROS.levelFlag =HIGHLEVEL, but it doesn't work, I only get the sensors.

please if you get it to work in ros, write me.  
And if it doesn't work with ros, how would I send the SLAM data generated in ROS to the SDK?

Thanks!

**Comment by gerardoportilla** [comment]
Hello 

I have found the SOLUTION!!!!!!!!
check this link .

https://github.com/unitreerobotics/unitree_ros_to_real/pull/25/commits/886beaca33aec04fbfc63c43207b553704df7eb8

replace the cmakelist.txt and also add the executable ros_server_udp.cpp
when you run  real.lauch and the  ros_server node.

in the file ros_server_udp.cpp you can put the commands.

Greetings.

**Comment by Taucrates** [comment]
Wow great!!. Thanks to you I was able to move the robot using the SDK. But now I'm trying to use the unitree_ros_to_real package and I'm not able to compile. Did you use the last version of SDK (3.5.1) or you're using the 3.4.1?

Thanks!!

**Comment by gerardoportilla** [comment]
hello,
I have uploaded it here, just run it directly, it already contains the SDK.

https://github.com/gerardoportilla/GO1_ros_real

**Comment by despargy** [comment]
hello,
I still have the problem of controlling in high level the Go1 through ROS, using unitree sdk, even when I used your repositories (that as you said solves the problem). 
 
I would be grateful if you could give me any hint to solve it!
Thank you!!

**Comment by gerardoportilla** [comment]
Hi despargy 

first check only with the SDK if the robot works to know that you have a good connection, (remember to use the levelFlag=0 in high level like walk)

now the repository that has recently been updated by unitree works very well and I would recommend you to use that one better, but you have to make some changes, with the following steps:

1) copy into your src folder, the robot's unitree_legged_sdk file and the unitree_ros_to_real file.

2) go to the CMakeLists.txt file, change the lines to these:

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -fPIC")

include_directories(
    include
    ${catkin_INCLUDE_DIRS}
    ${CMAKE_SOURCE_DIR}/unitree_legged_sdk/include
)
link_directories(${CMAKE_SOURCE_DIR}/unitree_legged_sdk/lib)


3) go to file example_walk.cpp and set this command = to zero like this.
   high_cmd_ros.levelFlag = 0

4) throw ros
roslaunch unitree_legged_real real.launch ctrl_level:=highlevel

5) then the node
rosrun unitree_legged_real example_walk

I hope it works for you, write me if you need to know more.
a greeting
