### ISSUE TITLE
connect A1 to internet

### ISSUE THREAD

**Issue by sasilva1998** [unitreerobotics/unitree_ros_to_real#31]
I got the Unitree A1 standard, I want to install some ROS packages (realsense) into the robot's raspberry, I already connected the raspy to a wifi network with internet, however, the raspy doesn't get any internet connection. I don't want to modify much of the network configs since I am afraid of breaking something.

I would like to know what I have to do to have internet connection in the robot's raspy or what is the best way to install ros packages there?

**Comment by TrivasZhang** [comment]
Directly use a usb-ethernet converter.
The new device will get a new IP to internet.

**Comment by MAVProxyUser** [comment]
You will have to pull down the eth0 wlan1 and ppp0 interfaces with ifconfig, because the routes will be broken.

**Comment by sasilva1998** [comment]
In the end I could connect to the internet using the usb-ethernet converter and installed intel realsense ros packages. Although I had to configure part of it but was not related to the default configs. Thanks for the help.

**Comment by sasilva1998** [comment]
In the end I could connect to the internet using the usb-ethernet converter and installed intel realsense ros packages. Although I had to configure part of it but was not related to the default configs. Thanks for the help.

**Comment by Maddy1206** [comment]
@sasilva1998 
@TrivasZhang 

I am reusing this topic to ask a related question regarding internet connection of the A1:

Suppose the Raspberry has internet connection, can the NX also connect to the internet over sharing?

Because I am currently trying to access the internet over the NX system but with no success so far. I tried using a usb-to-eth adapter and can ping from both sides but there is no internet connection established.

Regards

**Comment by Sergim96** [comment]
@Maddy1206 did you manage to provide internet access to the NX modules? 
I'm facing the same issues on B1

**Comment by Maddy1206** [comment]
@Sergim96 

I found the easiest way is to deactivate the RobotVisionSystem on start up, restart and connect the NX to WLAN like any other computer. 
If this does not satisfy your needs there is another way but I do not know if this does work for the B1.

**Comment by UnInterstedLedge** [comment]
> Directly use a usb-ethernet converter. The new device will get a new IP to internet.

To which port? The raspberry pi USB A port? Cause I'm trying to connect the GO1 pro to the internet

**Comment by Maddy1206** [comment]
@UnInterstedLedge 

Try the LAN port with an actual LAN cable instead.
