### ISSUE TITLE
Problem during compilation "catkin_make" with library "unitree_legged_sdk.h"

### ISSUE THREAD

**Issue by fLattes** [unitreerobotics/unitree_ros_to_real#36]
Hello, 

I have a problem during the compilation of the unitree_ros_to_real package. 
The cpp files in "unitree_ros_to_real" includes the library "unitree_legged_sdk/unitree_legged_sdk.h" but it seems that the program can't find the file.

This is the entire error, just after the compilation : 

/home/user/valkyrie/catkin_ws/src/unitree_ros_to_real/unitree_legged_real/src/exe/state_sub.cpp:10:10: fatal error: /home/robotec/valkyrie/catkin_ws/src/unitree_legged_sdk/include/unitree_legged_sdk/unitree_legged_sdk.h: No such file or directory
 #include </home/robotec/valkyrie/catkin_ws/src/unitree_legged_sdk/include/unitree_legged_sdk/unitree_legged_sdk.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
unitree_ros_to_real/unitree_legged_real/CMakeFiles/state_sub.dir/build.make:62: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/state_sub.dir/src/exe/state_sub.cpp.o' failed
make[2]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/state_sub.dir/src/exe/state_sub.cpp.o] Error 1
CMakeFiles/Makefile2:10761: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/state_sub.dir/all' failed
make[1]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/state_sub.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/user/valkyrie/catkin_ws/src/unitree_ros_to_real/unitree_legged_real/src/exe/twist_sub.cpp:6:10: fatal error: unitree_legged_sdk/unitree_legged_sdk.h: No such file or directory
 #include "unitree_legged_sdk/unitree_legged_sdk.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
unitree_ros_to_real/unitree_legged_real/CMakeFiles/twist_sub.dir/build.make:62: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/twist_sub.dir/src/exe/twist_sub.cpp.o' failed
make[2]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/twist_sub.dir/src/exe/twist_sub.cpp.o] Error 1
CMakeFiles/Makefile2:11025: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/twist_sub.dir/all' failed
make[1]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/twist_sub.dir/all] Error 2
/home/user/valkyrie/catkin_ws/src/unitree_ros_to_real/unitree_legged_real/src/exe/example_position.cpp:4:10: fatal error: unitree_legged_sdk/unitree_legged_sdk.h: No such file or directory
 #include "unitree_legged_sdk/unitree_legged_sdk.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_position.dir/build.make:62: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_position.dir/src/exe/example_position.cpp.o' failed
make[2]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_position.dir/src/exe/example_position.cpp.o] Error 1
CMakeFiles/Makefile2:10695: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_position.dir/all' failed
make[1]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_position.dir/all] Error 2
/home/user/valkyrie/catkin_ws/src/unitree_ros_to_real/unitree_legged_real/src/exe/ros_udp.cpp:6:10: fatal error: unitree_legged_sdk/unitree_legged_sdk.h: No such file or directory
 #include "unitree_legged_sdk/unitree_legged_sdk.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/user/valkyrie/catkin_ws/src/unitree_ros_to_real/unitree_legged_real/src/exe/example_walk.cpp:4:10: fatal error: unitree_legged_sdk/unitree_legged_sdk.h: No such file or directory
 #include "unitree_legged_sdk/unitree_legged_sdk.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
unitree_ros_to_real/unitree_legged_real/CMakeFiles/ros_udp.dir/build.make:62: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/ros_udp.dir/src/exe/ros_udp.cpp.o' failed
make[2]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/ros_udp.dir/src/exe/ros_udp.cpp.o] Error 1
CMakeFiles/Makefile2:10827: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/ros_udp.dir/all' failed
make[1]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/ros_udp.dir/all] Error 2
unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_walk.dir/build.make:62: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_walk.dir/src/exe/example_walk.cpp.o' failed
make[2]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_walk.dir/src/exe/example_walk.cpp.o] Error 1
CMakeFiles/Makefile2:10893: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_walk.dir/all' failed
make[1]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_walk.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

Thank you in advance for the help.

**Comment by 78748547** [comment]
> Hello,
> 
> I have a problem during the compilation of the unitree_ros_to_real package. The cpp files in "unitree_ros_to_real" includes the library "unitree_legged_sdk/unitree_legged_sdk.h" but it seems that the program can't find the file.
> 
> This is the entire error, just after the compilation :
> 
> /home/user/valkyrie/catkin_ws/src/unitree_ros_to_real/unitree_legged_real/src/exe/state_sub.cpp:10:10: fatal error: /home/robotec/valkyrie/catkin_ws/src/unitree_legged_sdk/include/unitree_legged_sdk/unitree_legged_sdk.h: No such file or directory #include </home/robotec/valkyrie/catkin_ws/src/unitree_legged_sdk/include/unitree_legged_sdk/unitree_legged_sdk.h> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. unitree_ros_to_real/unitree_legged_real/CMakeFiles/state_sub.dir/build.make:62: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/state_sub.dir/src/exe/state_sub.cpp.o' failed make[2]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/state_sub.dir/src/exe/state_sub.cpp.o] Error 1 CMakeFiles/Makefile2:10761: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/state_sub.dir/all' failed make[1]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/state_sub.dir/all] Error 2 make[1]: *** Waiting for unfinished jobs.... /home/user/valkyrie/catkin_ws/src/unitree_ros_to_real/unitree_legged_real/src/exe/twist_sub.cpp:6:10: fatal error: unitree_legged_sdk/unitree_legged_sdk.h: No such file or directory #include "unitree_legged_sdk/unitree_legged_sdk.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. unitree_ros_to_real/unitree_legged_real/CMakeFiles/twist_sub.dir/build.make:62: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/twist_sub.dir/src/exe/twist_sub.cpp.o' failed make[2]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/twist_sub.dir/src/exe/twist_sub.cpp.o] Error 1 CMakeFiles/Makefile2:11025: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/twist_sub.dir/all' failed make[1]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/twist_sub.dir/all] Error 2 /home/user/valkyrie/catkin_ws/src/unitree_ros_to_real/unitree_legged_real/src/exe/example_position.cpp:4:10: fatal error: unitree_legged_sdk/unitree_legged_sdk.h: No such file or directory #include "unitree_legged_sdk/unitree_legged_sdk.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_position.dir/build.make:62: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_position.dir/src/exe/example_position.cpp.o' failed make[2]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_position.dir/src/exe/example_position.cpp.o] Error 1 CMakeFiles/Makefile2:10695: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_position.dir/all' failed make[1]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_position.dir/all] Error 2 /home/user/valkyrie/catkin_ws/src/unitree_ros_to_real/unitree_legged_real/src/exe/ros_udp.cpp:6:10: fatal error: unitree_legged_sdk/unitree_legged_sdk.h: No such file or directory #include "unitree_legged_sdk/unitree_legged_sdk.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. /home/user/valkyrie/catkin_ws/src/unitree_ros_to_real/unitree_legged_real/src/exe/example_walk.cpp:4:10: fatal error: unitree_legged_sdk/unitree_legged_sdk.h: No such file or directory #include "unitree_legged_sdk/unitree_legged_sdk.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. unitree_ros_to_real/unitree_legged_real/CMakeFiles/ros_udp.dir/build.make:62: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/ros_udp.dir/src/exe/ros_udp.cpp.o' failed make[2]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/ros_udp.dir/src/exe/ros_udp.cpp.o] Error 1 CMakeFiles/Makefile2:10827: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/ros_udp.dir/all' failed make[1]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/ros_udp.dir/all] Error 2 unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_walk.dir/build.make:62: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_walk.dir/src/exe/example_walk.cpp.o' failed make[2]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_walk.dir/src/exe/example_walk.cpp.o] Error 1 CMakeFiles/Makefile2:10893: recipe for target 'unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_walk.dir/all' failed make[1]: *** [unitree_ros_to_real/unitree_legged_real/CMakeFiles/example_walk.dir/all] Error 2 Makefile:140: recipe for target 'all' failed make: *** [all] Error 2 Invoking "make -j12 -l12" failed
> 
> Thank you in advance for the help.

I also encountered the same problem. How did you solve it?
