### ISSUE TITLE
Go1 networking error while launching real.launch

### ISSUE THREAD

**Issue by JonasFovea** [unitreerobotics/unitree_ros_to_real#42]
Hi,

I'm trying to run the unitree_legged_real launch file but apparently something is wrong here.

```
$ roslaunch unitree_legged_real real.launch ctrl_level:=highlevel
      ... logging to /root/.ros/log/18f9dffc-d69c-11ec-8609-e45f018678a5/roslaunch-devicename-228.log
      Checking log directory for disk usage. This may take a while.
      Press Ctrl-C to interrupt
      Done checking log file disk usage. Usage is <1GB.
      
      RLException: Unable to contact my own server at [http://192.168.12.1:33367/].
      This usually means that the network is not configured properly.
      
      A common cause is that the machine cannot connect to itself.  Please check
      for errors by running:
      
              ping 192.168.12.1
      
      For more tips, please see
      
              http://wiki.ros.org/ROS/NetworkSetup
      
      The traceback for the exception was written to the log file
$  ping 192.168.12.1
      PING 192.168.12.1 (192.168.12.1) 56(84) bytes of data.
      64 bytes from 192.168.12.1: icmp_seq=1 ttl=64 time=3.40 ms
      64 bytes from 192.168.12.1: icmp_seq=2 ttl=64 time=2.98 ms
      64 bytes from 192.168.12.1: icmp_seq=3 ttl=64 time=3.47 ms
      ^C
      --- 192.168.12.1 ping statistics ---
      3 packets transmitted, 3 received, 0% packet loss, time 2003ms
      rtt min/avg/max/mdev = 2.984/3.285/3.469/0.214 ms

```

The connection to the roscore seems to be fine since I can view all the topics with `rostopic list`.
I am also able to reach all the devices in the `192.168.123.0` network...

Does somebody know, what I'm doing wrong?

Thanks in advance!

**Comment by Taucrates** [comment]
Hi Jonas,

Did you set the ROS_MASTER_URI?
If is not the case set it using:
export ROS_MASTER_URI=http://raspberrypi:11311

In my case raspberry is set in /etc/hosts file as 192.168.12.1

**Comment by JonasFovea** [comment]
Hey @Taucrates, 

thank you for your reply!

Yes I exported the URI, and I tried both options with hostname and ip.

As I mentioned the connection to the roscore is working, since I can view all existing topics on my machine...

Do you have any other idea?

**Comment by Taucrates** [comment]
Did you change the IP in the node launched in the real.launch? I  think the node is ros_udp.

**Comment by JonasFovea** [comment]
I've just now changed it to 192.168.12.1 with no effect.
Still the same output

**Comment by JonasFovea** [comment]
# Solved

So my assumption to use the ROS core on the robot was wrong.

Since the commands are sent to the robot via UDP, it is not necessary to connect the ROS systems.
Running a local ROS is all you need.
