### ISSUE TITLE
No ipconfig.sh file

### ISSUE THREAD

**Issue by 78748547** [unitreerobotics/unitree_ros_to_real#55]
Hello everyone, does anyone know where the `ipconfig.sh` file is? There are only five files (**CMakeLists.txt** **package.xml** **include** **launch** **src/exe** ) in the `unitree_legged_real` folder after I git clone these code. I can not find the `ipconfig.sh` file. The readme.md says "Then, open the ipconfig.sh file under the folder unitree_legged_real, modify the port name to your own. And run the following commands:". So, what should i do to modify the port name? My version is 3.80.

**Comment by scakki** [comment]
The 'ipconfig.sh' file seems to be missing in the 'master' branch but it's available in the 'foroldsdk' branch. Copy this file and paste it into the 'unitree_legged_real' folder, and the rest of it should be the same as the readme.md.

**Comment by scakki** [comment]
The ipconfig.sh file seems to be missing in the **master** branch but it's available in the **foroldsdk** branch. Copy this file and paste it into the **unitree_legged_real** folder, and the rest of it should be the same as the readme.md.

**Comment by 78748547** [comment]
> The ipconfig.sh file seems to be missing in the **master** branch but it's available in the **foroldsdk** branch. Copy this file and paste it into the **unitree_legged_real** folder, and the rest of it should be the same as the readme.md.

Thank you for your help
